<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
</head>

<body>
    <h3>数组降维</h3>
    <pre>
        const array = [1, [2, [3]]]
        array.flat() // [1, 2, [3]]
        array.flat(1) // [1, 2, [3]]，默认降 1 维
        array.flat(2) // [1, 2, 3]
        array.flat(3) // [1, 2, 3]，最多降到一维
      </pre>
    <h3>Promise 构造函数是同步执行的，promise.then 中的函数是异步执行的。</h3>
    <pre>
        const promise = new Promise((resolve, reject) => {
            console.log(1)
            resolve()
            console.log(2)
        })
        promise.then(() => {
            console.log(3)
        })
        console.log(4)

        // => 1
        // => 2
        // => 4
        // => 3
    </pre>
    <hr>
    <h3>js执行机制</h3>
    <pre>
        const first = () => (new Promise((resolve, reject) => {
            console.log(3);
            let p = new Promise((resolve, reject) => {
                console.log(7);
                setTimeout(() => {
                    console.log(5);
                    resolve(6);
                }, 0)
                resolve(1);
            });
            resolve(2);
            p.then((arg) => {
                console.log(arg);
            });
        
        }));
        
        first().then((arg) => {
            console.log(arg);
        });
        console.log(4);
        // => 3
        // => 7
        // => 4
        // => 1
        // => 2
        // => 5
    </pre>
    <h3>第一轮事件循环，先执行宏任务，主script，new Promise立即执行，输出 3，执行p这个new Promise操作，输出 7，发现setTimeout，将回调函数放入下一轮任务队列（Event Quene），
        p的then，暂且命名为then1，放入微任务队列，且first也有then，命名为then2，放入微任务队列。执行console.log(4),输出 4，宏任务执行结束。
        再执行微任务，执行then1,输出 1，执行then2,输出 3.
        第一轮事件循环结束，开始执行第二轮。第二轮事件循环先执行宏任务里面的，也就是setTimeout的回调，输出 5.resolve(6)不会生效，因为p的Promise状态一旦改变就不会再变化了。</h3>

    <hr>
    <pre>
        const promise1 = new Promise((resolve, reject) => {
            setTimeout(() => {
              resolve('success')
            }, 1000)
          })
          const promise2 = promise1.then(() => {
            throw new Error('error!!!')
          })
          
          console.log('promise1', promise1)
          console.log('promise2', promise2)
          
          setTimeout(() => {
            console.log('promise1', promise1)
            console.log('promise2', promise2)
          }, 2000)

          // =>    promise1 Promise {<pending>}
          // =>    promise2 Promise {<pending>}
          // =>    Uncaught (in promise) Error: error!!!
          // =>    at <anonymous>
          // =>    promise1 Promise {<resolved>: "success"}
          // =>    promise2 Promise {<rejected>: Error: error!!!
          // =>    at <anonymous>}
    </pre>
    <h3> promise 有 3 种状态：pending、fulfilled 或 rejected。状态改变只能是 pending->fulfilled 或者 pending->rejected，
        状态一旦改变则不能再变。上面 promise2 并不是 promise1，而是返回的一个新的 Promise 实例。</h3>
    <hr>
    <h3>构造函数中的 resolve 或 reject 只有第一次执行有效，多次调用没有任何作用，呼应代码二结论：promise 状态一旦改变则不能再变。</h3>
    <pre>
        const promise = new Promise((resolve, reject) => {
            resolve('success1')
            reject('error')
            resolve('success2')
          })
          
          promise
            .then((res) => {
              console.log('then: ', res)
            })
            .catch((err) => {
              console.log('catch: ', err)
            })
            // =>then: success1

            
    </pre>
    <hr>
    <h3>promise 可以链式调用。提起链式调用我们通常会想到通过 return this 实现，不过 Promise 并不是这样实现的。promise 每次调用 .then 或者 .catch 都会返回一个新的
        promise，从而实现了链式调用。</h3>
    <pre>
        Promise.resolve(1)
        .then((res) => {
          console.log(res)
          return 2
        })
        .catch((err) => {
          return 3
        })
        .then((res) => {
          console.log(res)
        })

        // => 1
        // => 2
    </pre>
    <hr>
    <h3>promise 的 .then 或者 .catch 可以被调用多次，但这里 Promise 构造函数只执行一次。或者说 promise 内部状态一经改变，并且有了一个值，那么后续每次调用 .then 或者 .catch
        都会直接拿到该值。</h3>
    <pre>
        const promise = new Promise((resolve, reject) => {
            setTimeout(() => {
              console.log('once')
              resolve('success')
            }, 1000)
          })
          
          const start = Date.now()
          promise.then((res) => {
            console.log(res, Date.now() - start)
          })
          promise.then((res) => {
            console.log(res, Date.now() - start)
          })

          // => once
          // => success 1000
          // => success 1000
    </pre>
    <hr>
    <pre>
        Promise.resolve()
        .then(() => {
            return new Error('error!!!')
        })
        .then((res) => {
            console.log('then: ', res)
        })
        .catch((err) => {
            console.log('catch: ', err)
        })

        // => then: Error: error!!! at <anonymous>:1:1
        
    </pre>
    <h3>.then 或者 .catch 中 return 一个 error 对象并不会抛出错误，所以不会被后续的 .catch 捕获，需要改成其中一种：
        return Promise.reject(new Error('error!!!'))
        throw new Error('error!!!')
        因为返回任意一个非 promise 的值都会被包裹成 promise 对象，即 return new Error('error!!!') 等价于 return Promise.resolve(new
        Error('error!!!'))。</h3>
    <hr>
    <h3>.then 或 .catch 返回的值不能是 promise 本身，否则会造成死循环。类似于：</h3>
    <pre>
            process.nextTick(function tick () {
                console.log('tick')
                process.nextTick(tick)
              })
        </pre>
    <pre>
            const promise = Promise.resolve()
            .then(() => {
                return promise
            })
            promise.catch(console.error)
            // => TypeError: Chaining cycle detected for promise #<Promise>
        </pre>
    <hr>
    <h3>.then 或者 .catch 的参数期望是函数，传入非函数则会发生值穿透。</h3>
    <pre>
            Promise.resolve(1)
            .then(2)
            .then(Promise.resolve(3))
            .then(console.log)

            // => 1
        </pre>
    <hr>
    <pre>
            Promise.resolve()
                .then(function success (res) {
                    throw new Error('error')
                }, function fail1 (e) {
                    console.error('fail1: ', e)
                })
                .catch(function fail2 (e) {
                    console.error('fail2: ', e)
                })

                // =>fail2:  Error: error!!! at <anonymous>:1:1
        </pre>
    <h3>.then 可以接收两个参数，第一个是处理成功的函数，第二个是处理错误的函数。
        .catch 是 .then 第二个参数的简便写法，但是它们用法上有一点需要注意：.then 的第二个处理错误的函数捕获不了第一个处理成功的函数抛出的错误，而后续的 .catch 可以捕获之前的错误。当然以下代码也可以：
    </h3>
    <pre>
                Promise.resolve()
                    .then(function success1 (res) {
                        throw new Error('error')
                    }, function fail1 (e) {
                        console.error('fail1: ', e)
                    })
                    .then(function success2 (res) {
                    }, function fail2 (e) {
                        console.error('fail2: ', e)
                    })
            </pre>
    <hr>
    <pre>
                process.nextTick(() => {
                    console.log('nextTick')
                  })
                  Promise.resolve()
                    .then(() => {
                      console.log('then')
                    })
                  setImmediate(() => {
                    console.log('setImmediate')
                  })
                  console.log('end')
                  // => 'end'
                  // => 'nextTick'
                  // => 'then'
                  // => 'setImmediate'
            </pre>
    <h3>
        process.nextTick 和 promise.then 都属于 micro task(微任务)，而 setImmediate 属于 macro task(宏任务)，在事件循环的 check
        阶段执行。事件循环的每个阶段（macrotask）之间都会执行 microtask，事件循环的开始会先执行一次 microtask。
    </h3>
    <hr>
    <h3 style="color: red;">红灯3秒亮一次，绿灯1秒亮一次，黄灯2秒亮一次；如何使用Promise让三个灯不断交替重复亮灯？</h3>
    <pre>
                1s 绿
                2s 绿 黄 
                3s 绿 红
                4s 绿 黄
                5s 绿
                6s 绿 黄 红
                7s 绿
                8s 绿 黄
                function transLight(){
                    return new Promise((res,rej)=>{
                        setTimeout()
                    })
                }
                
            </pre>
    <hr>
    <h3>
        请实现一个mergePromise函数，把传进去的数组按顺序先后执行，并且把返回的数据先后放到数组data中。
    </h3>
    <pre>
                const timeout = ms => new Promise((resolve, reject) => {
                    setTimeout(() => {
                        resolve();
                    }, ms);
                });
                
                const ajax1 = () => timeout(2000).then(() => {
                    console.log('1');
                    return 1;
                });
                
                const ajax2 = () => timeout(1000).then(() => {
                    console.log('2');
                    return 2;
                });
                
                const ajax3 = () => timeout(2000).then(() => {
                    console.log('3');
                    return 3;
                });
                
                const mergePromise = ajaxArray => {
                    // 在这里实现你的代码
                
                };
                
                mergePromise([ajax1, ajax2, ajax3]).then(data => {
                    console.log('done');
                    console.log(data); // data 为 [1, 2, 3]
                });
                // 要求分别输出
                // 1
                // 2
                // 3
                // done
                // [1, 2, 3]
            </pre>
</body>
<script>
    /**
    * 1.计算多个区间的交集
    *   区间用长度为2的数字数组表示，如[2, 5]表示区间2到5（包括2和5）；
    *   区间不限定方向，如[5, 2]等同于[2, 5]；
    *   实现`getIntersection 函数`
    *   可接收多个区间，并返回所有区间的交集（用区间表示），如空集用null表示
    * 示例：
    *   getIntersection([5, 2], [4, 9], [3, 6]); // [4, 5]
    *   getIntersection([1, 7], [8, 9]); // null
    */
    function getIntersection(...arg) {
        arg.forEach(item => {
            console.log(item)
        })
        // 1.找出数组中的每一个数 2 5
    }

    getIntersection([5, 2], [4, 9], [3, 6]);

</script>

</html>